name: CI

on:
  push:
    branches: [v4, main]
  pull_request:
    branches: [v4, main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          python download-deps.py --r no
          echo -e "y" | bash install-deps-linux.sh
      - name: Configure
        run: cmake -B build -S .
      - name: Build
        run: cmake --build build
